### ISSUE TITLE
ID & Hash Issue 

### ISSUE THREAD

**Issue by FaiekA** [PierreGode/MMM-next-episode#14]
Hi
The readme referances  "first 9 digits are the id and the rest is the hash"  
the string looks like this  'id=501bdxxx-9fxx-4dxx-bfxx-6b2bbbeaxxxx
Tried sever combination but no luck .
Any assistants - Thanks

**Comment by PierreGode** [comment]
Hi this is how the config should look like.
{
  module: "MMM-next-episode",
  position: "bottom_right",
  header: "Next-Episode",
  config: {
    id: '123456789',
    hash_key: 'a3a3a33aa333aaa333a3333333aa3333',
    username:'yourusename',
    password: 'yourpassword',
    displayShowingOn: true,
    displaySeasonAndEpisode: false,
    maxdays: 5,
    ShowThumbnail: true,
    ThumbnailSize: 'small',
    updateInterval: 180 // Update interval in minutes
  }
},

in your example is id: 501bdxxx9    hash_key: fxx4dxxbfxx6b2bbbeaxxxx

**Comment by FaiekA** [comment]
Hi - Yes it is  - Here my config 
		{
			module: "MMM-next-episode",
			position: "center",
			header: "Next-Episode",
			config: {
			  id: '501bdxxx9',
			  hash_key: 'ff14dxxbf076b2bbbeaxxx',
			  username: 'my username ',
			  password: 'my password',
			  displaySeasonAndEpisode: false,
			  displayShowingOn: false,
			  displayEpisodeName: false,
			  maxdays: 5,
			  ShowThumbnail: true,
			  ThumbnailSize: 'small',
			  updateInterval: 180
			}
		},  
I get it like this ---  'id=501bdxxx-9fxx-4dxx-bfxx-6b2bbbeaxxxx  from the QR link

**Comment by PierreGode** [comment]
Ok. lets verify this.

1. make sure you are on latest update 
`cd MagicMirror/modules/MMM-next-episode/ `
`git pull`

2. verify that you password does not have  special characters such as '+', '"', '^', '%', '$', '#', it can cause the link to break

3. restart pm2 and follow logs
`pm2 restart mm.sh`
`pm2 logs | grep next-episode`

**Comment by FaiekA** [comment]
make sure you are on latest update 
cd MagicMirror/modules/MMM-next-episode/ 
git pull   -        _Already up to date_ 

verify that you password does not have special characters such as '+', '"', '^', '%', '$', '#', it can cause the link to break
_**Change password to numeric value only**_ 

restart pm2 and follow logs --  _not using pm2 as this is a windows testing setup and not my main mirror_ 
_Nothing in the console - though_ 
console  logs 
`Load script: modules/MMM-next-episode/MMM-next-episode.js
module.js:480 Module registered: MMM-next-episode
loader.js:132 Bootstrapping module: MMM-next-episode
loader.js:136 Scripts loaded for: MMM-next-episode
loader.js:174 Load stylesheet: modules/MMM-next-episode/MMM-next-episode.css
loader.js:139 Styles loaded for: MMM-next-episode
loader.js:142 Translations loaded for: MMM-next-episode
MMM-next-episode.js:19 MMM-next-episode started!
MMM-next-episode.js:78 next-episode, Creating DOM elements
MMM-next-episode.js:28 next-episode, Received DATA notification with payload:  
MMM-next-episode.js:39 next-episode, Processing data:  
MMM-next-episode.js:73 next-episode, Final processed data:  Array(0)
MMM-next-episode.js:78 next-episode, Creating DOM elements
module.js:182 MMM-next-episode is suspended.
module.js:189 MMM-next-episode is resumed.`

**Comment by PierreGode** [comment]
Create this script verifyCon.mjs
with content:

```
import fetch from "node-fetch";

const Log = console; // Using the console for logging

// Configuration - Replace these values with actual id and hash_key for testing
const config = {
  id: "",
  hash_key: "",
};

async function verifyConnection(config) {
  const url = `https://next-episode.net/api/magicmirror/v1/services.php?service=next&user_id=${config.id}&hash_key=${config.hash_key}`;
  Log.log("verifyCon, Requesting data from: ", url);

  try {
    const response = await fetch(url);
    const body = await response.text();
    if (!response.ok || body.trim() === "") {
      throw new Error("Invalid response received from the API or empty response.");
    }

    Log.log("verifyCon, Successfully received data from the API: ", body);
    console.log("Success: Valid id and hash_key, data received from API.");
  } catch (error) {
    Log.error("verifyCon, Error in verifyConnection: ", error);
    console.error("Error: Invalid id or hash_key, or unable to fetch data from API.");
  }
}

// Run the verification
verifyConnection(config);
```


set the id and hash in the script
You need to: npm install node-fetch
and then
node verifyCon.mjs

It should give you a response: like verifyCon, Successfully received data from the API:  <?xml version="1.0" encoding="UTF-8"?>
<results>
        <result>
                <showid>20565</showid>
                <title>Pretty Little Liars: Original Sin</title>
                <hour>9:00</hour>
                <episodeName><![CDATA[Chapter Fourteen: When A Stranger Calls Back]]></episodeName>
                <episodeNumber>4</episodeNumber>
                <seasonNumber>2</seasonNumber>
                <imageUrl>https://static.next-episode.net/tv-shows-images/thumb/pretty-little-liars-original-sin.jpg?time=1676612104</imageUrl>
                <channel_name><![CDATA[HBO Max]]></channel_name>
                <countdown>Today</countdown>
        </result>

If this fails then we know something is up with your credentials.

**Comment by FaiekA** [comment]
Thank you - 
Looks like it the credentials 
PS C:\Users\Cash\Documents\MagicMirror\modules> node verifyCon.mjs
node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module 'C:\Users\Cash\Documents\MagicMirror\modules\verifyCon.mjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.12.2
PS C:\Users\Cash\Documents\MagicMirror\modules> node verifyCon.mjs
verifyCon, Requesting data from:  https://next-episode.net/api/magicmirror/v1/services.php?service=next&user_id=501bdf2d9&hash_key=ff14dd2bf076b2bbbeaa5f0
verifyCon, Error in verifyConnection:  Error: Invalid response received from the API or empty response.
    at verifyConnection (file:///C:/Users/Cash/Documents/MagicMirror/modules/verifyCon.mjs:19:13)    
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Invalid id or hash_key, or unable to fetch data from API.
PS C:\Users\Cash\Documents\MagicMirror\modules>

**Comment by FaiekA** [comment]
Ran it in the module folder - 
Same -- 
PS C:\Users\Cash\Documents\MagicMirror\modules\MMM-next-episode> node verifyCon.mjs
verifyCon, Requesting data from:  https://next-episode.net/api/magicmirror/v1/services.php?service=next&user_id=501bdf2d9&hash_key=ff14dd2bf076b2bbbeaa5f0
verifyCon, Error in verifyConnection:  Error: Invalid response received from the API or empty response.
    at verifyConnection (file:///C:/Users/Cash/Documents/MagicMirror/modules/MMM-next-episode/verifyCon.mjs:19:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Invalid id or hash_key, or unable to fetch data from API.
PS C:\Users\Cash\Documents\MagicMirror\modules\MMM-next-episode>

**Comment by PierreGode** [comment]
1. I would recommended to try to change your password, temporary to something simple and see that you get an different id and hash key.
2.  make sure you are following shows in the app. in "My Shows"

**Comment by PierreGode** [comment]
I deleted your comments. i think you accidentally posted your hash key.
anyway if that was the case. it seems that you only have the hash key and splitted the hash key. you are missing the ID.
try to  scan your QR code with an another device  and verify that you get both ID and hash.

**Comment by FaiekA** [comment]
Ok will do this evening - thanks

**Comment by FaiekA** [comment]
thank you so much for the assistant
simplified and the password and working
much appreciated
