### ISSUE TITLE
Episodes not displaying after latest update

### ISSUE THREAD

**Issue by vballnut** [PierreGode/MMM-next-episode#7]
I received notification of being a couple of commits behind and pulled the latest updates.  After that, the episodes stopped displaying on MM.  Do I need to make an update to the config or on my Next Episode account?  Thank you for any help!

**Comment by PierreGode** [comment]
Hi!
Sorry that you have issues.
can you try to go to /MagicMirror/modules/MMM-next-episode and run npm install and then restart the magic mirror?
best regards
Pierre

**Comment by vballnut** [comment]
Hi Pierre,

I’ve actually run npm install twice after the 2 pulls and have received the “already up to date” response. I have also run a clean install to make sure. I’m out of ideas. Hoping you have some :-)

Friday, January 12, 2024 at 12:55 AM -05:00 from ***@***.*** ***@***.***>:

**Comment by PierreGode** [comment]
As long you keep the config.js with the auth you can try to just delete the repository and clone it from start again.

Then in the folder
To make sure that all dependencies are installed, install them manually in the next-episode folder



npm install request
npm install qrcode
npm install uuid
npm install

Restart mm

**Comment by vballnut** [comment]
I have a backup of a pre-update version of my MM that I’m going to try first. If it works, I’ll probably just refrain from updating.

Friday, January 12, 2024 at 11:58 AM -05:00 from ***@***.*** ***@***.***>:
